### ISSUE TITLE
newgenome throws ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by fog-bank** [ganlab/GALA#11]
Hello,

Thank you for developing GALA. I have a problem with `newgenome` as follows.
```
$ /media/Users/src/GALA/newgenome drafts.txt gathering
Traceback (most recent call last):
  File "/media/Users/src/GALA/newgenome", line 28, in <module>
    genomes(genomes=draft,gathering=gathering,gathering_name=name,outpath=output)
  File "/media/Users/src/GALA/src/new_genome.py", line 82, in genomes
    b=new_genome(cut_file=gathering+gathering_name+'_'+a+'_cuts.txt',old_genome=aa,out_path=outpath,name='new_'+a)
  File "/media/Users/src/GALA/src/new_genome.py", line 48, in new_genome
    i[base+'_'+str(h)+'_'+'awad']=e[base][int(g[j]):int(g[j+1])]
ValueError: invalid literal for int() with base 10: '6067162.0'
```
Single command mode throws a similar error.
The content of `gathering/gathering_draft_01_cuts.txt`:
```
scaffold0003	6067162.0	4	3	0
...
scaffold0016	1397294.3333333333	3	2	0
```

I edited the `*_cuts.txt` files as all float values were trucated to integer values:
```
scaffold0003	6067162	4	3	0
...
scaffold0016	1397294	3	2	0
```
Then `newgenome` exited successfully. However, will the final result be expected?

Best

**Comment by fog-bank** [comment]
Sorry, I should use python2.
`python2 newgenome`
Thanks.

**Comment by execptionerror** [comment]
Already [[Solved] ValueError: invalid literal for int() with base 10](https://flutterq.com/valueerror-invalid-literal-for-int-with-base-10/)
