### ISSUE TITLE
How to run Gala

### ISSUE THREAD

**Issue by AstrMary** [ganlab/GALA#12]
Hello,
I have assembled a genome of 1.4 GBases with reads that come from MiNion  platform using CANU and Flye assembles and then I polished them with short reads that come from illumina using a number the Pilon , Polca and NextPolish tools. Now I want to try your tool but I don't understand if I run it with the proper way. Inside the  file  draft_names_paths.txt I insert all the polished  fasta genomes and the raw data (fastq.gz) of the MiNioN platform.

Then I run the command :  

./gala /data2/maria/assembles/draft_names_paths.txt  fq/fa corrected reads
Is it right ? 

Please help me,
Maria

**Comment by mawad89** [comment]
Hi Maria;
Firstly; GALA needs at least 3 assemblies to detect the mis-assemblies. but you can use it to construct the linkage groups directly from those assemblies if they are free of errors.

To run GALA you add only the preliminary assemblies (Flye and Canu) drafts to `draft_names_paths.txt` then run the following command:
` gala ./gala /data2/maria/assembles/draft_names_paths.txt fq  (fastq.gz full path) -nanopore-raw `

Also in your situation if you have only this two assemblies you can use the step by step module from step 5 **Contig Clustering Module (CCM)**. 

Mohamed

**Comment by AstrMary** [comment]
Mohamed thank you for your quick response..

I manage to run Gala tool as you wrote me and now I am waiting  the results :-)

Bests,
A.M
