### ISSUE TITLE
 I want to try CHM13 assembly

### ISSUE THREAD

**Issue by zhoudreames** [ganlab/GALA#13]
i want to try to assembly CHM13 before begin to my project,do you provide the assembley code about your article CHM13 assembly, thanks~

**Comment by zhoudreames** [comment]
@mawad89

**Comment by mawad89** [comment]
Hi @zhoudreames 
You can find it know on 

https://github.com/ganlab/GALA/tree/master/human_genome_pipeline

Best wishes
Mohamed

**Comment by zhoudreames** [comment]
> Hi @zhoudreames
> You can find it know on
> 
> https://github.com/ganlab/GALA/tree/master/human_genome_pipeline
> 
> Best wishes
> Mohamed

thanks~
