### ISSUE TITLE
Calculation time of bwa step 

### ISSUE THREAD

**Issue by kazuaki0816** [ganlab/GALA#14]
I performed GALA using the genome assembly files output by Canu (num_seqs: 45,165; sum_len: 5,369,907,803), Flye (num_seqs: 19,212; sum_len: 3,453,428,464) and wtdbg2  (num_seqs: 15,658; sum_len: 3,366,331,150), respectively.
The MDM module completed the calculation relatively quickly, but the later steps to use BWA took a lot of time.
The bwa calculation has been going on for about two weeks, is it possible to speed up this step?

I ran the following command.
$ vi draft_paths.txt
draft_01=/home/local/GALA/Assemblies/canu211-no2.contigs.fasta
draft_02=/home/local/GALA/Assemblies/flye.fasta
draft_03=/home/local/GALA/Assemblies/wtdbg2.fasta
$ gala draft_paths.txt fa /home/local/reads_files/1.fasta.gz pacbio-raw

**Comment by mawad89** [comment]
Hi @kazuaki0816 
If you work with a grid you can run the mapping steps in parallel mode manually. You can map the reads  to the error-free contigs. 
Best
