### ISSUE TITLE
How to assemble gap-free chomosome by gala according hifi and ONT data?

### ISSUE THREAD

**Issue by wzhangahas** [ganlab/GALA#16]
I have assembled 3 kinds of scafold by hifiasm, hicanu and falcon according Pacbio hifi data, at the same time, I have assembled another 3 kinds of scafold by nextdenovo, necat and flye, and polished them by nextpolish, I want to know how to assemble gap-free chomosome by gala according all the 6 kinds of  scafold. 
Thanks, 
Best regards.
Wei

**Comment by mawad89** [comment]
Hi Wei
First, prepare the draft_names_paths file included the six assemblies. Then go directly with MDM and CCM as described on the main page. In LGAM, you have the choice to continue with a nanopore, hifi, or both of them.
If it is not clear let me know

Best 
Mohamed

**Comment by wzhangahas** [comment]
Hi Mohamed,
The command as follow:
Linkage Group Assembly Module (LGAM)
8.Map all drafts against raw long reads and self-corrected reads if available.
# bwa index misassembly-free draft bwa mem -x pacbio/ont2d misassembly-free draft long-reads
How to use both of ONT and hifi as long-reads in the command line? Should I cat them together, and how to set -x ?
Thanks,
Best regards.
Wei

**Comment by mawad89** [comment]
If you want to use both datasets in the LGAM, map each of them separately. 
For Nanopore use
`bwa mem -x ont2d misassembly-free draft long-reads` or `minimap2 -ax map-ont draft.fa reads.fq`
For Hifi use
`minimap2 -ax asm20 draft.fa reads.fq`

**Comment by shiyi-pan** [comment]
Hi, I met the same problem, did you know how to do it?
I have Hifi and ONT data, too. Now I mapped each of them separately as suggested and separate the read names mapped to each contig. But I don't I don't know what to do next. Should I cat all reads from ONT and Hifi data that mapped to same contig together? If so, how to use one assembly software to assemble two different types of data?
best
