### ISSUE TITLE
The amount of data eventually generated

### ISSUE THREAD

**Issue by haiyun-fan** [ganlab/GALA#17]
After running lgam module, 201g data (FQ. GZ) is generated, while the original data is 93g (FQ. GZ)

**Comment by mawad89** [comment]
The LGAM module deal with each assembly in preliminary assemblies separately. So, it is generates fq.gz file for each linkage group in each preliminary assembly. If you want to reduce this amount of data you can run the step 11 for the linkage groups from only one of preliminary assemblies

Best
Mohamed
