### ISSUE TITLE
how  to prepare ref fasta file

### ISSUE THREAD

**Issue by wzhangahas** [ganlab/GALA#18]
When I cheack your ref (ref=../ref/GRCh38.p13.genome.fa) file in humen test, it has many lines that belong to 'chromosome 1', for example, $grep 'chromosome 1 ' GRCh38.p13.genome.fa, it shows many lines as follow:
>NT_187361.1 Homo sapiens chromosome 1 unlocalized genomic scaffold, GRCh38.p13 Primary Assembly HSCHR1_CTG1_UNLOCALIZED
>NT_187362.1 Homo sapiens chromosome 1 unlocalized genomic scaffold, GRCh38.p13 Primary Assembly HSCHR1_CTG2_UNLOCALIZED
>NT_187363.1 Homo sapiens chromosome 1 unlocalized genomic scaffold, GRCh38.p13 Primary Assembly HSCHR1_CTG3_UNLOCALIZED
>NT_187364.1 Homo sapiens chromosome 1 unlocalized genomic scaffold, GRCh38.p13 Primary Assembly HSCHR1_CTG4_UNLOCALIZED
......
So, could you please tell me how to prepare such ref file? 
Thanks, 
Best regards.

**Comment by mawad89** [comment]
Hi @wzhangahas 
The reference file is the  GRCh38 reference Human genome downloaded from NCBI -line 39 in the pipeline.sh -

Best
Mohamed

**Comment by wzhangahas** [comment]
Hi Mohamed, 
You are right, I have downloaded the GRCh38 reference Human genome according to Pipeline.sh. It was not chromosome-level genome file, I guess it was just scaffold file that was assembled by genome assembler. I want to know how to device the scaffolds into different chromosomes. 
Thanks, 
Wei

**Comment by mawad89** [comment]
Hi Wei;
Your information is not accurate. The downloaded file is in chromosome-level. The genome consists of 639 scaffold. 24 of them in the chromosome level.
```
NC_000001.11    248956422
NC_000002.12    242193529
NC_000003.12    198295559
NC_000004.12    190214555
NC_000005.10    181538259
NC_000006.12    170805979
NC_000007.14    159345973
NC_000008.11    145138636
NC_000009.12    138394717
NC_000010.11    133797422
NC_000011.10    135086622
NC_000012.12    133275309
NC_000013.11    114364328
NC_000014.9 107043718
NC_000015.10    101991189
NC_000016.10    90338345
NC_000017.11    83257441
NC_000018.10    80373285
NC_000019.10    58617616
NC_000020.11    64444167
NC_000021.9 46709983
NC_000022.11    50818468
NC_000023.11    156040895
NC_000024.10    57227415
```
The rest of scaffolds are Alt or unlocalized scaffolds. 

Best
Mohamed
