### ISSUE TITLE
How to deal with the same reads’ name?

### ISSUE THREAD

**Issue by wzhangahas** [ganlab/GALA#19]
When I check the different chromosomes reads’ names, there are some reads’ names belonged to different chromosomes, should we remove the same reads’ names in different chromosomes, or just keep them in different chromosomes? The size of chromosome 1 of Arabidopsis is 29.9M. When I assembled the fq of chromosome 1 of Arabidopsis with the same reads’ names by canu 2.0, the size of contig is 36.2M, and when I assembled the fq of chromosome 1 of Arabidopsis without the same reads’ names by canu 2.0, the size of contig is 19.6M.

**Comment by mawad89** [comment]
You don't need to delete anything. Use the fq file as it is. You can try delete the reads with low mapping quality (Ex: Q<10) but my  suggestion is to keep it.   
If the Chr1 size in Arabidopsis is 36.2M. usually you will find some contigs belongs to another chromosomes or duplicated contigs, ignore them.

**Comment by wzhangahas** [comment]
Hi Mohamed, 
Could you send your results about geneome assembly of Arabidopsis  by GALA? As I want to compare my results with yours. Thanks,
Wei







At 2021-06-17 14:26:27, "Mohamed Awad" ***@***.***> wrote:

You don't need to delete anything. Use the fq file as it is. You can try delete the reads with low mapping quality (Ex: Q<10) but my suggestion is to keep it.
If the Chr1 size in Arabidopsis is 36.2M. usually you will find some contigs belongs to another chromosomes or duplicated contigs, ignore them.

**Comment by mawad89** [comment]
Hi Wei
If you mean the assembly you can find it at https://doi.org/10.5281/zenodo.3840274. if you want something else let me know.

All the best;
Mohamed
