### ISSUE TITLE
How many draft assemblies should I need?

### ISSUE THREAD

**Issue by xiekunwhy** [ganlab/GALA#20]
Hi,

I have hifi and hic data of a species, I want to know that how many draft assemblies should I need if I want to use GALA? 4 assemblies generated from hifi data using different tools (hifiasm, flye, wtdbg2, raven) are enough?

Best,
Kun

**Comment by mawad89** [comment]
Hi Kun, 
Sorry for late responce it should be enough but maybe you will need to filtter the hifiasm contigs or use  only big contigs (-c 50000:80000)
Best
Mohamed
