### ISSUE TITLE
Single Command Mode: `KeyError:...

### ISSUE THREAD

**Issue by Ural-Yunusbaev** [ganlab/GALA#5]
Here I shared my files
https://drive.google.com/drive/folders/1CUCO74e_YArHYTAT92UdLcGiIgfPb9c-?usp=sharing

> Another bug!
> `'[M::main] CMD: minimap2 -x asm5 /home/crciv/AcerChrAssemb/GALA/gala/new_genomes/new_draft_3.fa /home/crciv/AcerChrAssemb/GALA/gala/new_genomes/new_draft_2.fa`
> `[M::main] Real time: 16.140 sec; CPU: 39.736 sec; Peak RSS: 1.634 GB`
> `Traceback (most recent call last):`
> ` File "/home/crciv/soft/gala/gala", line 82, in <module>`
> ` scaffolding(path='comparison',number_of_drafts=number_of_drafts,block=block,percentage=percent,shortage_contig=contig,quality=qty,out_file=True,output_name=name,output=outpath)`
> ` File "/home/crciv/soft/gala/src/scaffolding.py", line 163, in scaffolding`
> ` for bas in a[e][ba]:`
> `KeyError: 'Ctg8_pilon_1_awad'`

If you can share the files in gala_results/gap_free_comp/comparison folder with me (I tried different data-sets but I don't see this error)

_Originally posted by @mawad89 in https://github.com/ganlab/GALA/issues/1#issuecomment-630226359_

**Comment by mawad89** [comment]
Thanks for sharing your data. It is a mapping issue but I considered it and solved  in the new commit you can use it now.
Best wishes

**Comment by Ural-Yunusbaev** [comment]
Thanks, Mohamed!
