### ISSUE TITLE
KeyError: 'contig_2601_awad'

### ISSUE THREAD

**Issue by sadikmu** [ganlab/GALA#7]
Hi thanks for this great tool.

I am having failure at newgenome stage in both step-by-step and direct running mode.
Base environment: Python 2.7.15
Dependancies installed using conda after on Python  2.7.15 environment.

tail of std.err

```
`Traceback (most recent call last):
  File "/home/apps/gala/gala", line 98, in <module>
    scaffolding(path='comparison',number_of_drafts=number_of_drafts,block=block,percentage=percent,shortage_contig=contig,quality=qty,out_file=True,output_name=name,output=outpath)
  File "/home/apps/gala/src/scaffolding.py", line 250, in scaffolding
    zom=zom+int(a[ien][bac][0].split('\t')[1])
KeyError: 'contig_2601_awad'`
```

Any suggestions please

**Comment by mawad89** [comment]
Hi, 
the problem in ccm not in newgenome stage
I think this problem because the naming system 
if you have more than 9 drafts give the names like the below example:
```
draft01=path/to/draft
draft02=path/to/draft
draft03=path/to/draft
.
.
.
draft10=path/to/draft
draft11=path/to/draft
draft12=path/to/draft
```

Best wishes
Mohamed

**Comment by sadikmu** [comment]
hi @mawad89 ,

Thanks for your reply. 

I think I have placed fofn in draft_names_path.txt as described here but fail with error posted earlier.
```
draft01=/home/data/assembly/gala/canu.contigs.fasta
draft02=/home/data/assembly/gala/flye.contigs.fasta
```

**Comment by mawad89** [comment]
Okay 
You can try the last commit, and tell me if you still have the same problem or another one

All the best
Mohamed

**Comment by mawad89** [comment]
Any updates
