### ISSUE TITLE
How to get misassembly-free draft

### ISSUE THREAD

**Issue by lyrk50** [ganlab/GALA#9]
Hi,
I ran the ccm module and got three different new_draft.fa. Then I want to ran `bwa index misassembly-free draft`, but I have problems about how to get misassembly-free draft. Should I merge three different new_draft.fa? Hope to get your advice.

**Comment by mawad89** [comment]
Hi 
You can get the misassembly-free draft after run from MDM module.
1. use `mdm` to detect the mis-assembly.
2. use `newgenome` to produce misassembly-free draft from `mdm` output.

Also, it is possible to use any other method to detect and trim misassembled contigs then you can run the command. We developed each module to be completely independent.

**Comment by lyrk50** [comment]
Hi Mohamed,
Thanks for your reply. I use `newgenome` and get `new_draft_01.fa` `new_draft_02.fa` `new_draft_03.fa`. Then I want to run `LGAM` , should I merge three fasta files to get a new fasta or run them one by one?  Hope to get your advice.
Lynn

**Comment by mawad89** [comment]
Hi Lynn;
Run them one-by-one separately. In practice, if you have a lot of Preliminary drafts. using LGAM with 1-3 drafts gives a very good results. If anything unclear just drop a message.
All the best 
Mohamed

**Comment by lyrk50** [comment]
Hi Mohamed,
Thanks for your reply. I saw a sentence in your paper that
`This flexible framework also allows us to integrate data from various technologies,
such as Hi-C, genetic maps, a reference genome and even motif analyses, to generate gap-free chromosome-scale
assemblies. ` How can I use Hi-C data in this workflow?
Best wishes
Lynn

**Comment by mawad89** [comment]
Hi Lynn
You can use the Hi-C as one of preliminary assemblies. For Example you can use SALSA or Juicer, then use their draft as a preliminary draft. GALA enhanced Hi-C draft contiguity, correct its errors or misassemblies, and closed the gaps.

All my best wishes
Mohamed

**Comment by lyrk50** [comment]
Hi Mohamed,
Thanks you for the response.  If I use Juicer on my Hi-C data, which file format can be used as a preliminary draft? It seems like that no output file format is fasta.
Best wishes
Lynn

**Comment by mawad89** [comment]
Hi Lynn

Juicer gives a fasta file named as **assembly.FINAL.fasta**. SALSA gives a fasta file named **scaffolds_Final.fasta**.  GALA takes any of this files

Best wishes
Mohamed
